### PR TITLE
fix(credentials): Pass empty object to enable insecure connections

### PR DESCRIPTION
**Pull request by mgagliardo91**
## Expected Result

A user can create an insecure client with a preshared key and connect to spicedb without requiring SSL (docker / CI environments).

```js
const client = v1.NewClient(
  'token',
  'localhost:50051',
  v1.ClientSecurity.INSECURE_LOCALHOST_ALLOWED,
)
```

## Actual Result

The user will receive a gRPC connection error with code 14 and message `Last error: Credentials not loaded`.

## Changes

This client is using a custom Channel Credential class called `KnownInsecureChannelCredentialsImpl` which is a workaround to support insecure/non-SSL connections while still being able to pass metadata via the `createFromMetadataGenerator()` middleware.

The following commit in [grpc](https://github.com/grpc/grpc/tree/master) (see https://github.com/grpc/grpc-node/commit/ed53ea644cdc24b4d945ed5340df4c8867f2f98c#diff-7c43d37a239cc91464d8ba94c2ece274bdf5146da1442603b7dc9fdd9b4f8483R184) broke the ability to return `null` from the `_getConnectionOptions()` class method, which led to the custom class usage to break.

This fix re-aligns the `KnownInsecureChannelCredentialsImpl` back with the grpc equivalent to re-allow insecure credential passing so that users can use authzed-nodejs against CI environments.

### CODE REVIEW

**Comment by mgagliardo91** [comment]
@ecordell See attached. The associated thread in Discord is at https://discord.com/channels/844600078504951838/844600078948630559/1294349459228065853

**Comment by mgagliardo91** [comment]
recheck

**Comment by mgagliardo91** [comment]
Based on historical commits, also tagging @tstirrat15

**Review by tstirrat15 — APPROVED** [review]
I chatted with the PR author and it sounds like this is a backwards-compatible change. Let's get this in and I'll get a release cut.

**Comment by tstirrat15** [comment]
This should fix #166, but I'll wait for confirmation there before closing.

**Pull request merged**
