### PR TITLE
docs: fix user reference in the README

### PR DESCRIPTION
**Pull request by pierr**
There is an error  in the main doc of the package.
image

### CODE REVIEW

**Comment by vroldanbet** [comment]
@pierr thanks for your contribution, please sign the CLA

**Comment by pierr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by pierr** [comment]
@vroldanbet this is ✅

**Review by vroldanbet — APPROVED** [review]

**Comment by pierr** [comment]
@vroldanbet It seems the build is not triggered properly

**Comment by vroldanbet** [comment]
@pierr yeah, the filters used to bypass GitHub Actions cause this on required builds. I'll force merge for now.

**Pull request merged**
