### PR TITLE
Release v0.8.0

### PR DESCRIPTION
**Pull request by mgagliardo91**
I wasn't quite sure of who is in charge of getting releases out, but I was hoping to go ahead and get the following PRs into a versioned release into NPM:

- https://github.com/authzed/authzed-node/pull/28
- https://github.com/authzed/authzed-node/pull/40

### CODE REVIEW

**Comment by mgagliardo91** [comment]
recheck

**Comment by mgagliardo91** [comment]
@samkim is there a better process for PR reviews? I'm not sure if I should be tagging individuals directly

**Comment by samkim** [comment]
Apologies! I'll review this PR and I opened a PR to add a codeowners file so that future PRs are auto assigned.

**Comment by mgagliardo91** [comment]
> Apologies! I'll review this PR and I opened a PR to add a codeowners file so that future PRs are auto assigned.

Thanks @samkim !

**Review by samkim — APPROVED** [review]
LGTM

**Pull request merged**
